#!/usr/bin/env python3
"""Generate SKILLS.md catalog from plugin SKILL.md frontmatter.

Walks plugins/*/skills/*/SKILL.md (excluding vendored upstream/ trees),
groups by plugin, and writes SKILLS.md at the repo root. Also prints a
reality report — the actual counts per plugin — so docs can be checked
against drift.

Run from repo root: python3 scripts/build_catalog.py
Writes: SKILLS.md
Always exits 0 (drift inspection is for the human, not the gate).
"""
import glob
import os
import re
import sys
from collections import defaultdict
from pathlib import Path


SKIP_PARTS = {"upstream"}


def parse_frontmatter(path: str) -> dict[str, str]:
    content = Path(path).read_text(encoding="utf-8", errors="replace")
    if not content.startswith("---"):
        return {}
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}
    fm = parts[1]
    out: dict[str, str] = {}
    name = re.search(r"^name:\s*[\"']?([^\"'\n]+?)[\"']?\s*$", fm, re.M)
    if name:
        out["name"] = name.group(1).strip()
    desc = re.search(r"^description:\s*[\"']?(.+?)[\"']?\s*$", fm, re.M)
    if desc:
        out["description"] = desc.group(1).strip().rstrip('"').rstrip("'")
    return out


def scan_skills() -> dict[str, list[dict]]:
    skills_by_plugin: dict[str, list[dict]] = defaultdict(list)
    for sm in sorted(glob.glob("plugins/*/skills/*/SKILL.md")):
        if any(part in SKIP_PARTS for part in sm.split(os.sep)):
            continue
        plugin = sm.split(os.sep)[1]
        fm = parse_frontmatter(sm)
        if not fm.get("name"):
            continue
        skills_by_plugin[plugin].append({
            "name": fm["name"],
            "description": fm.get("description", ""),
            "path": sm,
        })
    return dict(skills_by_plugin)


def write_catalog(skills_by_plugin: dict[str, list[dict]]) -> int:
    total = sum(len(s) for s in skills_by_plugin.values())
    out: list[str] = []
    out.append("# MStack Skills Catalog")
    out.append("")
    out.append("> Auto-generated by `scripts/build_catalog.py` — run `make catalog` to refresh.")
    out.append("> Source of truth: each plugin's SKILL.md frontmatter. Do not hand-edit this file.")
    out.append("")
    out.append(f"**Total**: {total} skills across {len(skills_by_plugin)} plugins.")
    out.append("")
    out.append("---")
    out.append("")
    for plugin in sorted(skills_by_plugin):
        skills = sorted(skills_by_plugin[plugin], key=lambda s: s["name"])
        out.append(f"## `{plugin}` — {len(skills)} skills")
        out.append("")
        for s in skills:
            desc = s["description"]
            if len(desc) > 220:
                desc = desc[:220].rstrip() + "…"
            out.append(f"- **{s['name']}** — {desc}")
        out.append("")
    Path("SKILLS.md").write_text("\n".join(out), encoding="utf-8")
    return total


def main() -> int:
    skills_by_plugin = scan_skills()
    total = write_catalog(skills_by_plugin)
    print(f"[OK] Wrote SKILLS.md - {total} skills across {len(skills_by_plugin)} plugins\n")
    print("Reality report (use to spot drift in docs):")
    print(f"  Total skills:  {total}")
    print(f"  Plugins:       {len(skills_by_plugin)}")
    print("  Per plugin:")
    for p in sorted(skills_by_plugin):
        print(f"    {p:<25} {len(skills_by_plugin[p])}")
    print("")
    print("To grep docs for hardcoded counts:")
    print("  grep -nE '[0-9]+ (PM )?skills?' README.md CLAUDE.md AGENTS.md \\")
    print("       .claude-plugin/marketplace.json plugins/*/.claude-plugin/plugin.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
